//
// Opcode to implementation map.
//
// Copyright (C) 2023 Walt Drummond
//
// This program is free software: you can redistribute it and/or modify it
// under the terms of the GNU General Public License as published by the Free
// Software Foundation, either version 3 of the License, or (at your option)
// any later version.
//
// This program is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of  MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
// more details.
//
// You should have received a copy of the GNU General Public License along with
// this program.  If not, see <http://www.gnu.org/licenses/>.

#include "./6502.h"

// The instructions.  Flags field provides information about any special
// handling the current instruction requires.  For the 6502, the flags
// are:
//  - InstructionFlags::Branch: Add a cycle if conditional branch is taken (all
//                  conditional branches).
//  - CYCLE__PAGE : Add two cycles if an instruction causes a read from
//                  an address on an adjacent page, specifically indexed
//                  addressing modes.
//
// See http://www.6502.org/users/obelisk/6502/addressing.html for more
// information.

std::map<Byte, MOS6502::instruction> MOS6502::setupInstructionMap() {
	return  {
		{ Opcodes::INS_BRK_IMP,
		  {"brk", AddressingMode::Implied, 1, 7, InstructionFlags::None, &MOS6502::ins_brk}},
		{ Opcodes::INS_ORA_IDX,
		  {"ora", AddressingMode::IndirectX, 2, 6, InstructionFlags::None, &MOS6502::ins_ora}},
		{ Opcodes::INS_ASL_ACC,
		  {"asl", AddressingMode::Accumulator, 1, 2, InstructionFlags::None, &MOS6502::ins_asl}},
		{ Opcodes::INS_ADC_ZP,
		  {"adc", AddressingMode::ZeroPage, 2, 3, InstructionFlags::None, &MOS6502::ins_adc}},
		{ Opcodes::INS_ROR_ZP,
		  {"ror", AddressingMode::ZeroPage, 2, 5, InstructionFlags::None, &MOS6502::ins_ror}},
		{ Opcodes::INS_PLA_IMP,
		  {"pla", AddressingMode::Implied, 1, 4, InstructionFlags::None, &MOS6502::ins_pla}},
		{ Opcodes::INS_ADC_IMM,
		  {"adc", AddressingMode::Immediate, 2, 2, InstructionFlags::None, &MOS6502::ins_adc}},
		{ Opcodes::INS_ROR_ACC,
		  {"ror", AddressingMode::Accumulator, 1, 2, InstructionFlags::None, &MOS6502::ins_ror}},
		{ Opcodes::INS_JMP_IND,
		  {"jmp", AddressingMode::Indirect, 3, 5, InstructionFlags::None, &MOS6502::ins_jmp}},
		{ Opcodes::INS_ADC_ABS,
		  {"adc", AddressingMode::Absolute, 3, 4, InstructionFlags::None, &MOS6502::ins_adc}},
		{ Opcodes::INS_ROR_ABS,
		  {"ror", AddressingMode::Absolute, 3, 6, InstructionFlags::None, &MOS6502::ins_ror}},
		{ Opcodes::INS_BVS_REL,
		  {"bvs", AddressingMode::Relative, 2, 2, InstructionFlags::Branch, &MOS6502::ins_bvs}},
		{ Opcodes::INS_ADC_IDY,
		  {"adc", AddressingMode::IndirectY, 2, 5, InstructionFlags::PageBoundary, &MOS6502::ins_adc}},
		{ Opcodes::INS_ADC_ZPX,
		  {"adc", AddressingMode::ZeroPageX, 2, 4, InstructionFlags::None, &MOS6502::ins_adc}},
		{ Opcodes::INS_ROR_ZPX,
		  {"ror", AddressingMode::ZeroPageX, 2, 6, InstructionFlags::None, &MOS6502::ins_ror}},
		{ Opcodes::INS_SEI_IMP,
		  {"sei", AddressingMode::Implied, 1, 2, InstructionFlags::None, &MOS6502::ins_sei}},
		{ Opcodes::INS_ADC_ABY,
		  {"adc", AddressingMode::AbsoluteY, 3, 4, InstructionFlags::PageBoundary, &MOS6502::ins_adc}},
		{ Opcodes::INS_ADC_ABX,
		  {"adc", AddressingMode::AbsoluteX, 3, 4, InstructionFlags::PageBoundary, &MOS6502::ins_adc}},
		{ Opcodes::INS_ROR_ABX,
		  {"ror", AddressingMode::AbsoluteX, 3, 7, InstructionFlags::None, &MOS6502::ins_ror}},
		{ Opcodes::INS_STA_IDX,
		  {"sta", AddressingMode::IndirectX, 2, 6, InstructionFlags::None, &MOS6502::ins_sta}},
		{ Opcodes::INS_ORA_ABS,
		  {"ora", AddressingMode::Absolute, 3, 4, InstructionFlags::None, &MOS6502::ins_ora}},
		{ Opcodes::INS_STY_ZP,
		  {"sty", AddressingMode::ZeroPage, 2, 3, InstructionFlags::None, &MOS6502::ins_sty}},
		{ Opcodes::INS_STA_ZP,
		  {"sta", AddressingMode::ZeroPage, 2, 3, InstructionFlags::None, &MOS6502::ins_sta}},
		{ Opcodes::INS_STX_ZP,
		  {"stx", AddressingMode::ZeroPage, 2, 3, InstructionFlags::None, &MOS6502::ins_stx}},
		{ Opcodes::INS_DEY_IMP,
		  {"dey", AddressingMode::Implied, 1, 2, InstructionFlags::None, &MOS6502::ins_dey}},
		{ Opcodes::INS_TXA_IMP,
		  {"txa", AddressingMode::Implied, 1, 2, InstructionFlags::None, &MOS6502::ins_txa}},
		{ Opcodes::INS_ASL_ABS,
		  {"asl", AddressingMode::Absolute, 3, 6, InstructionFlags::None, &MOS6502::ins_asl}},
		{ Opcodes::INS_STY_ABS,
		  {"sty", AddressingMode::Absolute, 3, 4, InstructionFlags::None, &MOS6502::ins_sty}},
		{ Opcodes::INS_STA_ABS,
		  {"sta", AddressingMode::Absolute, 3, 4, InstructionFlags::None, &MOS6502::ins_sta}},
		{ Opcodes::INS_STX_ABS,
		  {"stx", AddressingMode::Absolute, 3, 4, InstructionFlags::None, &MOS6502::ins_stx}},
		{ Opcodes::INS_BCC_REL,
		  {"bcc", AddressingMode::Relative, 2, 2, InstructionFlags::Branch, &MOS6502::ins_bcc}},
		{ Opcodes::INS_STA_IDY,
		  {"sta", AddressingMode::IndirectY, 2, 6, InstructionFlags::None, &MOS6502::ins_sta}},
		{ Opcodes::INS_STY_ZPX,
		  {"sty", AddressingMode::ZeroPageX, 2, 4, InstructionFlags::None, &MOS6502::ins_sty}},
		{ Opcodes::INS_STA_ZPX,
		  {"sta", AddressingMode::ZeroPageX, 2, 4, InstructionFlags::None, &MOS6502::ins_sta}},
		{ Opcodes::INS_STX_ZPY,
		  {"stx", AddressingMode::ZeroPageY, 2, 4, InstructionFlags::None, &MOS6502::ins_stx}},
		{ Opcodes::INS_TYA_IMP,
		  {"tya", AddressingMode::Implied, 1, 2, InstructionFlags::None, &MOS6502::ins_tya}},
		{ Opcodes::INS_STA_ABY,
		  {"sta", AddressingMode::AbsoluteY, 3, 5, InstructionFlags::None, &MOS6502::ins_sta}},
		{ Opcodes::INS_TXS_IMP,
		  {"txs", AddressingMode::Implied, 1, 2, InstructionFlags::None, &MOS6502::ins_txs}},
		{ Opcodes::INS_STA_ABX,
		  {"sta", AddressingMode::AbsoluteX, 3, 5, InstructionFlags::None, &MOS6502::ins_sta}},
		{ Opcodes::INS_BPL_REL,
		  {"bpl", AddressingMode::Relative, 2, 2, InstructionFlags::Branch, &MOS6502::ins_bpl}},
		{ Opcodes::INS_LDY_IMM,
		  {"ldy", AddressingMode::Immediate, 2, 2, InstructionFlags::None, &MOS6502::ins_ldy}},
		{ Opcodes::INS_LDA_IDX,
		  {"lda", AddressingMode::IndirectX, 2, 6, InstructionFlags::None, &MOS6502::ins_lda}},
		{ Opcodes::INS_LDX_IMM,
		  {"ldx", AddressingMode::Immediate, 2, 2, InstructionFlags::None, &MOS6502::ins_ldx}},
		{ Opcodes::INS_LDY_ZP,
		  {"ldy", AddressingMode::ZeroPage, 2, 3, InstructionFlags::None, &MOS6502::ins_ldy}},
		{ Opcodes::INS_LDA_ZP,
		  {"lda", AddressingMode::ZeroPage, 2, 3, InstructionFlags::None, &MOS6502::ins_lda}},
		{ Opcodes::INS_LDX_ZP,
		  {"ldx", AddressingMode::ZeroPage, 2, 3, InstructionFlags::None, &MOS6502::ins_ldx}},
		{ Opcodes::INS_TAY_IMP,
		  {"tay", AddressingMode::Implied, 1, 2, InstructionFlags::None, &MOS6502::ins_tay}},
		{ Opcodes::INS_LDA_IMM,
		  {"lda", AddressingMode::Immediate, 2, 2, InstructionFlags::None, &MOS6502::ins_lda}},
		{ Opcodes::INS_ORA_IDY,
		  {"ora", AddressingMode::IndirectY, 2, 5, InstructionFlags::PageBoundary, &MOS6502::ins_ora}},
		{ Opcodes::INS_TAX_IMP,
		  {"tax", AddressingMode::Implied, 1, 2, InstructionFlags::None, &MOS6502::ins_tax}},
		{ Opcodes::INS_LDY_ABS,
		  {"ldy", AddressingMode::Absolute, 3, 4, InstructionFlags::None, &MOS6502::ins_ldy}},
		{ Opcodes::INS_LDA_ABS,
		  {"lda", AddressingMode::Absolute, 3, 4, InstructionFlags::None, &MOS6502::ins_lda}},
		{ Opcodes::INS_LDX_ABS,
		  {"ldx", AddressingMode::Absolute, 3, 4, InstructionFlags::None, &MOS6502::ins_ldx}},
		{ Opcodes::INS_BCS_REL,
		  {"bcs", AddressingMode::Relative, 2, 2, InstructionFlags::Branch, &MOS6502::ins_bcs}},
		{ Opcodes::INS_LDA_IDY,
		  {"lda", AddressingMode::IndirectY, 2, 5, InstructionFlags::PageBoundary, &MOS6502::ins_lda}},
		{ Opcodes::INS_LDY_ZPX,
		  {"ldy", AddressingMode::ZeroPageX, 2, 4, InstructionFlags::None, &MOS6502::ins_ldy}},
		{ Opcodes::INS_LDA_ZPX,
		  {"lda", AddressingMode::ZeroPageX, 2, 4, InstructionFlags::None, &MOS6502::ins_lda}},
		{ Opcodes::INS_LDX_ZPY,
		  {"ldx", AddressingMode::ZeroPageY, 2, 4, InstructionFlags::None, &MOS6502::ins_ldx}},
		{ Opcodes::INS_CLV_IMP,
		  {"clv", AddressingMode::Implied, 1, 2, InstructionFlags::None, &MOS6502::ins_clv}},
		{ Opcodes::INS_LDA_ABY,
		  {"lda", AddressingMode::AbsoluteY, 3, 4, InstructionFlags::PageBoundary, &MOS6502::ins_lda}},
		{ Opcodes::INS_TSX_IMP,
		  {"tsx", AddressingMode::Implied, 1, 2, InstructionFlags::None, &MOS6502::ins_tsx}},
		{ Opcodes::INS_LDY_ABX,
		  {"ldy", AddressingMode::AbsoluteX, 3, 4, InstructionFlags::PageBoundary, &MOS6502::ins_ldy}},
		{ Opcodes::INS_LDA_ABX,
		  {"lda", AddressingMode::AbsoluteX, 3, 4, InstructionFlags::PageBoundary, &MOS6502::ins_lda}},
		{ Opcodes::INS_LDX_ABY,
		  {"ldx", AddressingMode::AbsoluteY, 3, 4, InstructionFlags::PageBoundary, &MOS6502::ins_ldx}},
		{ Opcodes::INS_CPY_IMM,
		  {"cpy", AddressingMode::Immediate, 2, 2, InstructionFlags::None, &MOS6502::ins_cpy}},
		{ Opcodes::INS_CMP_IDX,
		  {"cmp", AddressingMode::IndirectX, 2, 6, InstructionFlags::None, &MOS6502::ins_cmp}},
		{ Opcodes::INS_CPY_ZP,
		  {"cpy", AddressingMode::ZeroPage, 2, 3, InstructionFlags::None, &MOS6502::ins_cpy}},
		{ Opcodes::INS_CMP_ZP,
		  {"cmp", AddressingMode::ZeroPage, 2, 3, InstructionFlags::None, &MOS6502::ins_cmp}},
		{ Opcodes::INS_DEC_ZP,
		  {"dec", AddressingMode::ZeroPage, 2, 5, InstructionFlags::None, &MOS6502::ins_dec}},
		{ Opcodes::INS_INY_IMP,
		  {"iny", AddressingMode::Implied, 1, 2, InstructionFlags::None, &MOS6502::ins_iny}},
		{ Opcodes::INS_CMP_IMM,
		  {"cmp", AddressingMode::Immediate, 2, 2, InstructionFlags::None, &MOS6502::ins_cmp}},
		{ Opcodes::INS_DEX_IMP,
		  {"dex", AddressingMode::Implied, 1, 2, InstructionFlags::None, &MOS6502::ins_dex}},
		{ Opcodes::INS_CPY_ABS,
		  {"cpy", AddressingMode::Absolute, 3, 4, InstructionFlags::None, &MOS6502::ins_cpy}},
		{ Opcodes::INS_CMP_ABS,
		  {"cmp", AddressingMode::Absolute, 3, 4, InstructionFlags::None, &MOS6502::ins_cmp}},
		{ Opcodes::INS_DEC_ABS,
		  {"dec", AddressingMode::Absolute, 3, 6, InstructionFlags::None, &MOS6502::ins_dec}},
		{ Opcodes::INS_BNE_REL,
		  {"bne", AddressingMode::Relative, 2, 2, InstructionFlags::Branch, &MOS6502::ins_bne}},
		{ Opcodes::INS_CMP_IDY,
		  {"cmp", AddressingMode::IndirectY, 2, 5, InstructionFlags::PageBoundary, &MOS6502::ins_cmp}},
		{ Opcodes::INS_ORA_ZPX,
		  {"ora", AddressingMode::ZeroPageX, 2, 4, InstructionFlags::None, &MOS6502::ins_ora}},
		{ Opcodes::INS_CMP_ZPX,
		  {"cmp", AddressingMode::ZeroPageX, 2, 4, InstructionFlags::None, &MOS6502::ins_cmp}},
		{ Opcodes::INS_DEC_ZPX,
		  {"dec", AddressingMode::ZeroPageX, 2, 6, InstructionFlags::None, &MOS6502::ins_dec}},
		{ Opcodes::INS_CLD_IMP,
		  {"cld", AddressingMode::Implied, 1, 2, InstructionFlags::None, &MOS6502::ins_cld}},
		{ Opcodes::INS_CMP_ABY,
		  {"cmp", AddressingMode::AbsoluteY, 3, 4, InstructionFlags::PageBoundary, &MOS6502::ins_cmp}},
		{ Opcodes::INS_ASL_ZPX,
		  {"asl", AddressingMode::ZeroPageX, 2, 6, InstructionFlags::None, &MOS6502::ins_asl}},
		{ Opcodes::INS_CMP_ABX,
		  {"cmp", AddressingMode::AbsoluteX, 3, 4, InstructionFlags::PageBoundary, &MOS6502::ins_cmp}},
		{ Opcodes::INS_DEC_ABX,
		  {"dec", AddressingMode::AbsoluteX, 3, 7, InstructionFlags::None, &MOS6502::ins_dec}},
		{ Opcodes::INS_CPX_IMM,
		  {"cpx", AddressingMode::Immediate, 2, 2, InstructionFlags::None, &MOS6502::ins_cpx}},
		{ Opcodes::INS_SBC_IDX,
		  {"sbc", AddressingMode::IndirectX, 2, 6, InstructionFlags::None, &MOS6502::ins_sbc}},
		{ Opcodes::INS_CPX_ZP,
		  {"cpx", AddressingMode::ZeroPage, 2, 3, InstructionFlags::None, &MOS6502::ins_cpx}},
		{ Opcodes::INS_SBC_ZP,
		  {"sbc", AddressingMode::ZeroPage, 2, 3, InstructionFlags::None, &MOS6502::ins_sbc}},
		{ Opcodes::INS_INC_ZP,
		  {"inc", AddressingMode::ZeroPage, 2, 5, InstructionFlags::None, &MOS6502::ins_inc}},
		{ Opcodes::INS_INX_IMP,
		  {"inx", AddressingMode::Implied, 1, 2, InstructionFlags::None, &MOS6502::ins_inx}},
		{ Opcodes::INS_SBC_IMM,
		  {"sbc", AddressingMode::Immediate, 2, 2, InstructionFlags::None, &MOS6502::ins_sbc}},
		{ Opcodes::INS_NOP_IMP,
		  {"nop", AddressingMode::Implied, 1, 2, InstructionFlags::None, &MOS6502::ins_nop}},
		{ Opcodes::INS_CPX_ABS,
		  {"cpx", AddressingMode::Absolute, 3, 4, InstructionFlags::None, &MOS6502::ins_cpx}},
		{ Opcodes::INS_SBC_ABS,
		  {"sbc", AddressingMode::Absolute, 3, 4, InstructionFlags::None, &MOS6502::ins_sbc}},
		{ Opcodes::INS_INC_ABS,
		  {"inc", AddressingMode::Absolute, 3, 6, InstructionFlags::None, &MOS6502::ins_inc}},
		{ Opcodes::INS_CLC_IMP,
		  {"clc", AddressingMode::Implied, 1, 2, InstructionFlags::None, &MOS6502::ins_clc}},
		{ Opcodes::INS_BEQ_REL,
		  {"beq", AddressingMode::Relative, 2, 2, InstructionFlags::Branch, &MOS6502::ins_beq}},
		{ Opcodes::INS_SBC_IDY,
		  {"sbc", AddressingMode::IndirectY, 2, 5, InstructionFlags::PageBoundary, &MOS6502::ins_sbc}},
		{ Opcodes::INS_SBC_ZPX,
		  {"sbc", AddressingMode::ZeroPageX, 2, 4, InstructionFlags::None, &MOS6502::ins_sbc}},
		{ Opcodes::INS_INC_ZPX,
		  {"inc", AddressingMode::ZeroPageX, 2, 6, InstructionFlags::None, &MOS6502::ins_inc}},
		{ Opcodes::INS_SED_IMP,
		  {"sed", AddressingMode::Implied, 1, 2, InstructionFlags::None, &MOS6502::ins_sed}},
		{ Opcodes::INS_SBC_ABY,
		  {"sbc", AddressingMode::AbsoluteY, 3, 4, InstructionFlags::PageBoundary, &MOS6502::ins_sbc}},
		{ Opcodes::INS_ORA_ABY,
		  {"ora", AddressingMode::AbsoluteY, 3, 4, InstructionFlags::PageBoundary, &MOS6502::ins_ora}},
		{ Opcodes::INS_SBC_ABX,
		  {"sbc", AddressingMode::AbsoluteX, 3, 4, InstructionFlags::PageBoundary, &MOS6502::ins_sbc}},
		{ Opcodes::INS_INC_ABX,
		  {"inc", AddressingMode::AbsoluteX, 3, 7, InstructionFlags::None, &MOS6502::ins_inc}},
		{ Opcodes::INS_ORA_ABX,
		  {"ora", AddressingMode::AbsoluteX, 3, 4, InstructionFlags::PageBoundary, &MOS6502::ins_ora}},
		{ Opcodes::INS_ASL_ABX,
		  {"asl", AddressingMode::AbsoluteX, 3, 7, InstructionFlags::None, &MOS6502::ins_asl}},
		{ Opcodes::INS_JSR_ABS,
		  {"jsr", AddressingMode::Absolute, 3, 6, InstructionFlags::None, &MOS6502::ins_jsr}},
		{ Opcodes::INS_AND_IDX,
		  {"and", AddressingMode::IndirectX, 2, 6, InstructionFlags::None, &MOS6502::ins_and}},
		{ Opcodes::INS_BIT_ZP,
		  {"bit", AddressingMode::ZeroPage, 2, 3, InstructionFlags::None, &MOS6502::ins_bit}},
		{ Opcodes::INS_AND_ZP,
		  {"and", AddressingMode::ZeroPage, 2, 3, InstructionFlags::None, &MOS6502::ins_and}},
		{ Opcodes::INS_ROL_ZP,
		  {"rol", AddressingMode::ZeroPage, 2, 5, InstructionFlags::None, &MOS6502::ins_rol}},
		{ Opcodes::INS_PLP_IMP,
		  {"plp", AddressingMode::Implied, 1, 4, InstructionFlags::None, &MOS6502::ins_plp}},
		{ Opcodes::INS_AND_IMM,
		  {"and", AddressingMode::Immediate, 2, 2, InstructionFlags::None, &MOS6502::ins_and}},
		{ Opcodes::INS_ROL_ACC,
		  {"rol", AddressingMode::Accumulator, 1, 2, InstructionFlags::None, &MOS6502::ins_rol}},
		{ Opcodes::INS_BIT_ABS,
		  {"bit", AddressingMode::Absolute, 3, 4, InstructionFlags::None, &MOS6502::ins_bit}},
		{ Opcodes::INS_AND_ABS,
		  {"and", AddressingMode::Absolute, 3, 4, InstructionFlags::None, &MOS6502::ins_and}},
		{ Opcodes::INS_ROL_ABS,
		  {"rol", AddressingMode::Absolute, 3, 6, InstructionFlags::None, &MOS6502::ins_rol}},
		{ Opcodes::INS_BMI_REL,
		  {"bmi", AddressingMode::Relative, 2, 2, InstructionFlags::Branch, &MOS6502::ins_bmi}},
		{ Opcodes::INS_AND_IDY,
		  {"and", AddressingMode::IndirectY, 2, 5, InstructionFlags::PageBoundary, &MOS6502::ins_and}},
		{ Opcodes::INS_ORA_ZP, 
		  {"ora", AddressingMode::ZeroPage, 2, 3, InstructionFlags::None, &MOS6502::ins_ora}},
		{ Opcodes::INS_AND_ZPX,
		  {"and", AddressingMode::ZeroPageX, 2, 4, InstructionFlags::None, &MOS6502::ins_and}},
		{ Opcodes::INS_ROL_ZPX,
		  {"rol", AddressingMode::ZeroPageX, 2, 6, InstructionFlags::None, &MOS6502::ins_rol}},
		{ Opcodes::INS_SEC_IMP,
		  {"sec", AddressingMode::Implied, 1, 2, InstructionFlags::None, &MOS6502::ins_sec}},
		{ Opcodes::INS_AND_ABY,
		  {"and", AddressingMode::AbsoluteY, 3, 4, InstructionFlags::PageBoundary, &MOS6502::ins_and}},
		{ Opcodes::INS_ASL_ZP, 
		  {"asl", AddressingMode::ZeroPage, 2, 5, InstructionFlags::None, &MOS6502::ins_asl}},
		{ Opcodes::INS_AND_ABX,
		  {"and", AddressingMode::AbsoluteX, 3, 4, InstructionFlags::PageBoundary, &MOS6502::ins_and}},
		{ Opcodes::INS_ROL_ABX,
		  {"rol", AddressingMode::AbsoluteX, 3, 7, InstructionFlags::None, &MOS6502::ins_rol}},
		{ Opcodes::INS_RTI_IMP,
		  {"rti", AddressingMode::Implied, 1, 6, InstructionFlags::None, &MOS6502::ins_rti}},
		{ Opcodes::INS_EOR_IDX,
		  {"eor", AddressingMode::IndirectX, 2, 6, InstructionFlags::None, &MOS6502::ins_eor}},
		{ Opcodes::INS_EOR_ZP,
		  {"eor", AddressingMode::ZeroPage, 2, 3, InstructionFlags::None, &MOS6502::ins_eor}},
		{ Opcodes::INS_LSR_ZP,
		  {"lsr", AddressingMode::ZeroPage, 2, 5, InstructionFlags::None, &MOS6502::ins_lsr}},
		{ Opcodes::INS_PHA_IMP,
		  {"pha", AddressingMode::Implied, 1, 3, InstructionFlags::None, &MOS6502::ins_pha}},
		{ Opcodes::INS_EOR_IMM,
		  {"eor", AddressingMode::Immediate, 2, 2, InstructionFlags::None, &MOS6502::ins_eor}},
		{ Opcodes::INS_LSR_ACC,
		  {"lsr", AddressingMode::Accumulator, 1, 2, InstructionFlags::None, &MOS6502::ins_lsr}},
		{ Opcodes::INS_JMP_ABS,
		  {"jmp", AddressingMode::Absolute, 3, 3, InstructionFlags::None, &MOS6502::ins_jmp}},
		{ Opcodes::INS_EOR_ABS,
		  {"eor", AddressingMode::Absolute, 3, 4, InstructionFlags::None, &MOS6502::ins_eor}},
		{ Opcodes::INS_LSR_ABS,
		  {"lsr", AddressingMode::Absolute, 3, 6, InstructionFlags::None, &MOS6502::ins_lsr}},
		{ Opcodes::INS_PHP_IMP,
		  {"php", AddressingMode::Implied, 1, 3, InstructionFlags::None, &MOS6502::ins_php}},
		{ Opcodes::INS_BVC_REL,
		  {"bvc", AddressingMode::Relative, 2, 2, InstructionFlags::Branch, &MOS6502::ins_bvc}},
		{ Opcodes::INS_EOR_IDY,
		  {"eor", AddressingMode::IndirectY, 2, 5, InstructionFlags::PageBoundary, &MOS6502::ins_eor}},
		{ Opcodes::INS_EOR_ZPX,
		  {"eor", AddressingMode::ZeroPageX, 2, 4, InstructionFlags::None, &MOS6502::ins_eor}},
		{ Opcodes::INS_LSR_ZPX,
		  {"lsr", AddressingMode::ZeroPageX, 2, 6, InstructionFlags::None, &MOS6502::ins_lsr}},
		{ Opcodes::INS_CLI_IMP,
		  {"cli", AddressingMode::Implied, 1, 2, InstructionFlags::None, &MOS6502::ins_cli}},
		{ Opcodes::INS_EOR_ABY,
		  {"eor", AddressingMode::AbsoluteY, 3, 4, InstructionFlags::PageBoundary, &MOS6502::ins_eor}},
		{ Opcodes::INS_ORA_IMM,
		  {"ora", AddressingMode::Immediate, 2, 2, InstructionFlags::None, &MOS6502::ins_ora}},
		{ Opcodes::INS_EOR_ABX,
		  {"eor", AddressingMode::AbsoluteX, 3, 4, InstructionFlags::PageBoundary, &MOS6502::ins_eor}},
		{ Opcodes::INS_LSR_ABX,
		  {"lsr", AddressingMode::AbsoluteX, 3, 7, InstructionFlags::None, &MOS6502::ins_lsr}},
		{ Opcodes::INS_RTS_IMP,
		  {"rts", AddressingMode::Implied, 1, 6, InstructionFlags::None, &MOS6502::ins_rts}},
		{ Opcodes::INS_ADC_IDX,
		  {"adc", AddressingMode::IndirectX, 2, 6, InstructionFlags::None, &MOS6502::ins_adc}},
	};
}
